server:
  port: 80

spring:
  application:
    name: crow-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  routes:
    portal:
      service-id: crow-authenticate
      path: /**
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000


