spring:
  datasource:
    username: root
    password: cjcisgood
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.52.132:3306/cjcfunding?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml




